
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    rapidAPIKey: 'ed6875d1d5msh808d68b9ee3b655p154363jsn5c63964dd2b3'
  };
